# Generated by Django 2.0 on 2018-01-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnlist',
            name='bind_mac',
            field=models.BooleanField(),
        ),
    ]
