# Generated by Django 2.0 on 2018-01-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnmanage', '0002_auto_20180108_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnlist',
            name='bind_ip',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='dev_outip',
        ),
        migrations.RemoveField(
            model_name='vpnlist',
            name='use_proxy_svn',
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='bind_mac',
            field=models.CharField(max_length=30),
        ),
    ]
