# Generated by Django 2.0 on 2018-01-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpnmanage', '0003_auto_20180108_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnlist',
            name='bind_mac',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='default_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='project_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vpnlist',
            name='user',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
