# Generated by Django 2.0 on 2018-01-09 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpnmanage', '0004_auto_20180108_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpnlist',
            old_name='vpn_2ip',
            new_name='vpn2_ip',
        ),
    ]
