# Generated by Django 2.0 on 2018-01-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vpnmanage', '0005_auto_20180109_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vpnlist',
            name='default_password',
        ),
    ]
